Mummur: initial murmur-core and murmur-cli implementations [2][4]
ideal-lab5/murmur pull request #5
Opened 2024-09-17 17:20 UTC by driemworks

Closes #2 
Closes #4 

- [x] separates original implementation (cli only) into cli and core repositories
- [x] murmur-core: implements the create, execute, and verify algorithms
- [x] murmur-cli: allows ephemeral mmr wallet creation, execution, and scheduled execution
- [x] no_std compat
- [ ] wasm build

2024-09-24 14:53 UTC, juangirini requested changes
Aside from the many (but trivial) requests, there are a few things that can be addressed:
- Link task for error handling
- Link task for zeroize
Things that need to be done in this PR:
- clippy + formatting
- tests

2024-09-24 14:53 UTC, juangirini commented on Cargo.toml
> +
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on Cargo.toml
> +# sp-application-crypto = { git = "https://github.com/ideal-lab5/polkadot-sdk.git", branch = "testing", features = ["bls-experimental"] }
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on Cargo.toml
> +# # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on Cargo.toml
> +# array-bytes = "6.1"
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on cli/Cargo.toml
> +# etf-crypto-primitives = { path = "../etf-sdk/etf-crypto-primitives" }
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on cli/Cargo.toml
> +# blake2b = "0.10.6"
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on cli/Cargo.toml
> +# bytes = "1.4.0"
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on cli/Cargo.toml
> +# node-template-runtime = { git = "https://github.com/ideal-lab5/etf.git", branch = "tony/dev" }
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on cli/README.md
> +./target/debug/node --tmp --dev --alice --unsafe-rpc-external --rpc-cors all
This should be fine for local testing
```suggestion
./target/debug/node --dev
```

2024-09-24 14:53 UTC, juangirini commented on cli/README.md
> +-
```suggestion
- run an [IDN node](https://github.com/ideal-lab5/etf)
```

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +    Execute(WalletExecuteDetails),
```suggestion
    /// Create a new Murmur wallet
    New(WalletCreationDetails),
    /// Dispatch (proxy) a call to a Murmur wallet in the future
    ScheduleExecute(WalletExecuteDetails),
    /// Dispatch (proxy) a call to a Murmur wallet
    Execute(WalletExecuteDetails),
```

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +}
Do we need it?

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +            validator_set_id: 0, // TODO: how to ensure correct validator set ID is used? could just always set to 1 for now, else set input param.
Do we have an issue for it?

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +    // let round_pubkey = DoublePublicKey::<TinyBLS377>::from_bytes(&round_pubkey_bytes).unwrap();
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +    let etf = OnlineClient::<SubstrateConfig>::new().await?;
I have the same question :D

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +    // TODO: HKDF? just hash the seed?
Do we have a task for it?

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +            // TODO: make the origin configurable
Do we have a task for it?

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +            let from = dev::alice();
Is this the sponsor/master account? If so, we should abstract it away so we can configure it later on

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +        // },
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +            // TODO: cleanup type defs
task?

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +            // store.to_mmr(&mut mmr).unwrap();
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +                // etf.clone(),
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +                .sign_and_submit_then_watch_default(&tx, &dev::alice())
Same as above

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +/// -> add this to the 'future work' section later
```suggestion
/// Prepare the call for immediate execution
// Note: in the future, we can consider ways to prune the murmurstore as OTP codes are consumed
//     for example, we can take the next values from the map, reducing storage to 0 over time
//     However, to do this we need to think of a way to prove it with a merkle proof
//     my though is that we would have a subtree, so first we prove that the subtree is indeed in the parent MMR
//     then we prove that the specific leaf is in the subtree.
//  We could potentially use that idea as a way to optimize the execute function in general. Rather than
//  loading the entire MMR into memory, we really only need to load a  minimal subtree containing the leaf we want to consume
// -> add this to the 'future work' section later
```

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +/// read an MMR from a file
```suggestion
/// Read an MMR from a file
```

2024-09-24 14:53 UTC, juangirini commented on cli/src/main.rs
> +// }
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on core/Cargo.toml
> +    # "rand_core/std",
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on core/Cargo.toml
> +# 1.8.1
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on core/src/murmur.rs
> +}
```suggestion
/// The murmur store
#[cfg(feature = "client")]
#[derive(Clone, serde::Serialize, serde::Deserialize)]
pub struct MurmurStore {
    /// Map block numbers to positions in the mmr
    pub metadata: BTreeMap<BlockNumber, Ciphertext>,
    /// The root of the mmr
    pub root: Leaf,
}
```

2024-09-24 14:53 UTC, juangirini commented on core/src/murmur.rs
> +    ///
```suggestion
    /// Creates the leaves needed to generate an MMR
    /// This function generates otp codes for the given block schedule
    /// then it encrypts the resulting codes and constructs leaves 
    /// the leaves can be used to generate an MMR
```

2024-09-24 14:53 UTC, juangirini commented on core/src/murmur.rs
> +    /// TODO: this should probably be a result, not option
```suggestion
    /// Build the parameters needed to use a murmur wallet
    /// note: this rebuilds the entire mmr
    /// we can look into ways to optimize this in the future
    /// the main issue is that he MemStore is not serializable
    /// a possible fix is to externalize mmr logic
    // TODO: this should probably be a result, not option
```

Do we have a task for the TODO ?

2024-09-24 14:53 UTC, juangirini commented on core/src/murmur.rs
> +    ///      output from IDN for `when`
```suggestion
    /// Use the seed to commit to some data at a specific block number
    /// i.e. this commit cannot be verified until there is a signature
    /// output from IDN for `when`
```

2024-09-24 14:53 UTC, juangirini commented on core/src/murmur.rs
> +    /// builds an mmr from the mmr store
```suggestion
    /// Builds an mmr from the mmr store
```

2024-09-24 14:53 UTC, juangirini commented on core/src/murmur.rs
> +/// timelock encryption function
```suggestion
/// Timelock encryption function
```

2024-09-24 14:53 UTC, juangirini commented on core/src/murmur.rs
> +        OsRng, // TODO
?

2024-09-24 14:53 UTC, juangirini commented on core/src/murmur.rs
> +/// build a block-otp generator from the seed
```suggestion
/// Build a block-otp generator from the seed
```

2024-09-24 14:53 UTC, juangirini commented on core/src/murmur.rs
> +	    // let msk = keypair.secret.0; // can destroy this
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on core/src/murmur.rs
> +        //
```suggestion
```

2024-09-24 14:53 UTC, juangirini commented on core/src/otp.rs
> +}
```suggestion
/// A block based otp generator
pub struct BOTPGenerator {
    /// The time-based otp generator
    totp: TOTP
}
```

2024-09-24 14:53 UTC, juangirini commented on core/src/otp.rs
> +    /// create a new BOTP generator with the given seed
```suggestion
    /// Create a new BOTP generator with the given seed
```

2024-09-24 14:53 UTC, juangirini commented on core/src/otp.rs
> +    /// generate an otp code
```suggestion
    /// Generate an otp code
```

2024-09-24 14:53 UTC, juangirini commented on core/src/types.rs
> +/// the type to represent a block number
```suggestion
/// The type to represent a block number
```

2024-09-24 14:53 UTC, juangirini commented on core/src/types.rs
> +/// merge leaves together with a sha256 hasher
```suggestion
/// Merge leaves together with a sha256 hasher
```

2024-09-24 14:53 UTC, juangirini commented on core/src/types.rs
> +/// something that builds unique identities (e.g. using crypto hash function) for any block number
```suggestion
/// Something that builds unique identities (e.g. using crypto hash function) for any block number
```

2024-09-24 14:53 UTC, juangirini commented on test
> +adsfadsfasdfasdfasdf
This file needs to be gone

2024-09-25 11:37 UTC, juangirini commented on cli/src/main.rs
> +pub struct BasicIdBuilder;
Should we move this builder to the `core` crate and make it `Default`? We could then use it in other crates (`murmur-core-wasm`) without having to depend on `cli`

2024-09-25 13:51 UTC, driemworks commented on cli/src/main.rs
> +pub struct BasicIdBuilder;
The BasicIdBuilder relies on beefy primitives (for constructing the payload and commitment), I think it'd be better to not include that dependency in murmur-core.

2024-09-25 17:21 UTC, driemworks commented on core/src/murmur.rs
> +        OsRng, // TODO
Left as a todo since we could replace OsRng with something else, e.g. ChaCha20Rng, but it's fine for now

2024-09-26 15:29 UTC, juangirini commented on cli/src/main.rs
> +pub struct BasicIdBuilder;
fair enough

2024-09-26 15:36 UTC, juangirini reviewed
Looks mostly good, still a few comments from the last review not addressed

2024-09-26 15:36 UTC, juangirini commented on Cargo.toml
> +repository = "https://github.com/ideal-lab5/etf"
```suggestion
repository = "https://github.com/ideal-lab5/murmur"
```

2024-09-26 15:36 UTC, juangirini commented on cli/src/main.rs
> +    // pub fn test_can_read_write_mmr_store() { }
```suggestion
    // TODO
```

2024-09-26 15:36 UTC, juangirini commented on core/src/murmur.rs
> +            let _pos = mmr.push(leaf).expect("todo");//.map_err(|e| {
```suggestion
            let _pos = mmr.push(leaf).expect("todo");
```

2024-09-26 15:36 UTC, juangirini commented on core/src/murmur.rs
> +        OsRng, // TODO
makes sense, let's add what you say to the comment in the code

2024-09-26 16:21 UTC, colemanirby approved these changes

2024-09-27 14:48 UTC, juangirini commented on core/Cargo.toml
> +
This is why we need to mention `package = "murmur-core"` when we import this crate in other Cargo.toml files

```suggestion
```

2024-09-28 21:28 UTC, driemworks commented on cli/src/main.rs
> +            validator_set_id: 0, // TODO: how to ensure correct validator set ID is used? could just always set to 1 for now, else set input param.
No, we should create a more high level backlog item to track this.

2024-09-28 21:28 UTC, driemworks commented on cli/src/main.rs
> +    // TODO: HKDF? just hash the seed?
yes

2024-09-28 21:29 UTC, driemworks commented on cli/src/main.rs
> +            // TODO: make the origin configurable
We don't, but it's not needed for the scope of the hackathon. Will need to create a more high level backlog item to track these items.

2024-09-28 21:30 UTC, driemworks commented on cli/src/main.rs
> +            let from = dev::alice();
not sure I follow. For the hackathon/demo purpose, it seems fine to just hard-code alice for the time being (e.g. the user never has to know about this origin)

2024-09-28 21:32 UTC, driemworks commented on cli/src/main.rs
> +    let etf = OnlineClient::<SubstrateConfig>::new().await?;
I can't resolve this for some reason, but this line no longer exists.

2024-09-29 22:33 UTC, driemworks commented on cli/src/main.rs
> +            let from = dev::alice();
leaving as is for now, tracking in issue: https://github.com/orgs/ideal-lab5/projects/8?pane=issue&itemId=81495895

2024-09-29 22:33 UTC, driemworks commented on cli/src/main.rs
> +                .sign_and_submit_then_watch_default(&tx, &dev::alice())
same as above: https://github.com/orgs/ideal-lab5/projects/8?pane=issue&itemId=81495895

2024-09-29 22:35 UTC, driemworks commented on cli/src/main.rs
> +            // TODO: make the origin configurable
tracking in: https://github.com/orgs/ideal-lab5/projects/8?pane=issue&itemId=81495984

2024-09-30 09:24 UTC, juangirini approved these changes

2024-09-30 13:25 UTC, merged